- name: setup certbot apt repo
  become: true
  apt_repository:
    repo: "ppa:certbot/certbot"
- name: install nginx and certbot
  become: true
  apt:
    force_apt_get: yes
    name: ["nginx", "python-certbot-nginx"]
    update_cache: yes