- name: setup nginx reverse proxy
  become: yes
  template:
    src: templates/nginx.j2
    dest: /etc/nginx/sites-available/{{ https_reverse_proxy_site_name }}
  notify:
    - test nginx configuration
- name: put reverse proxy site config in enabled
  become: yes
  file:
    src: /etc/nginx/sites-available/{{ https_reverse_proxy_site_name }}
    dest: /etc/nginx/sites-enabled/{{ https_reverse_proxy_site_name }}
    state: link
  notify:
    - test nginx configuration
- name: reload nginx service
  become: yes
  service:
    name: nginx
    state: reloaded
    enabled: yes